package:
  name: solprop_ml
  version: 1.0

source:
  path: ../

build:
    noarch: python
    number: '0'
    string: py_0
    
requirements:
  host:
    - python >=3.7
    - setuptools

  run:
    - python >=3.7
    - matplotlib
    - numpy
    - pandas
    - pytorch
    - rdkit
    - scikit-learn
    - tensorboardX
    - tqdm
    - coolprop
    - chemprop_solvation >=0.0.3
about:
    home: https://github.com/fhvermei/SolPropML
extra:
    copy_test_source_files: true
    final: true
